# Generated by Django 2.1.2 on 2018-11-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewLostDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(max_length=50)),
                ('crew_avatar_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('crew_phone', models.CharField(max_length=50)),
                ('crew_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_pet_pointing', models.CharField(max_length=50)),
                ('lost_pet_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('person_phone', models.CharField(max_length=50)),
                ('person_email', models.CharField(max_length=50)),
                ('person_birthday', models.CharField(max_length=50)),
                ('person_personal_photo', models.CharField(max_length=50)),
                ('person_personal_pet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_age', models.CharField(max_length=50)),
                ('pet_birthday', models.CharField(max_length=50)),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_breed', models.CharField(max_length=50)),
                ('pet_chip_number', models.CharField(max_length=50)),
                ('pet_lost_flag', models.BooleanField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_avatar_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_phone', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
            ],
        ),
    ]
