# Generated by Django 2.1.2 on 2018-11-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181115_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='person_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
