# Generated by Django 2.1.2 on 2018-11-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181120_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
