# Generated by Django 2.1.2 on 2018-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181120_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_age',
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=70),
        ),
    ]
